валидация формы
htmlacademy-javascript/925273-kekstagram-22 pull request #7
Opened 2021-02-26 08:48 UTC by irus994

2021-02-27 12:10 UTC, StGeass requested changes

2021-02-27 12:10 UTC, StGeass commented on js/validation.js
> +    } else {
Вот так не надо делать, ты по сути только что обнулила все проверки выше, потому что не прошла конкретно эта

Но если как я писал выше будешь прерывать цикл на первой ошибке, то всё будет ок

Главное приоритизовать ошибки, т.е. наиболее базовые должны быть выше остальных, например проверка на пустую строку выше чем проверка на правильность символов хештега и т.д.

2021-02-28 11:13 UTC, irus994 commented on js/validation.js
> +    for (let j = 1; j < hashtag.length; j++) {
я пока не знаю как это сделать регулярными выражениями, пытаюсь освоить  хотя бы что понимаю более менее и не распыляться

2021-02-28 11:48 UTC, irus994 commented on js/validation.js
> +    if (!(new Set(hashtags).size === hashtags.length)) {
Перенесла выше

2021-02-28 11:55 UTC, irus994 commented on js/validation.js
> +export {hashtagsInput}
написала

2021-02-28 16:37 UTC, irus994 commented on js/slider.js
> +  if (evt.keyCode === 27 && !((commentTextInput === document.activeElement) || (hashtagsInput === document.activeElement))) {
исправила

2021-02-28 21:05 UTC, irus994 commented on js/validation.js
> +  for (let i = 0; i < hashtags.length; i++) {
Вроде исправила

2021-03-01 11:16 UTC, merged